# PLEASE UPDATE THE PACKAGES LIST APPROPRIATELY.
packages:
  - "containers/*"
  - "lambdas/*"

engineStrict: true
minimumReleaseAge: 2880
nodeOptions: "${NODE_OPTIONS:- } --experimental-vm-modules"
trustPolicy: no-downgrade
trustPolicyExclude:
  - "semver@6.3.1"
blockExoticSubdeps: true
ignoreDepScripts: true

overrides:
  collect-v8-coverage: "^1.0.3"
  fast-xml-parser: "^5.5.6"
  flatted: "^3.4.0"
  pretty-format>react-is: "19.0.0"
  react: "^19.0.0"
  ts-jest>handlebars: "^4.7.9"

catalogs:
  lint:
    "@eslint/js": "^9.39.4"
    "@next/eslint-plugin-next": "^15.3.2"
    "@stylistic/eslint-plugin": "^5.10.0"
    "@typescript-eslint/parser": "^8.57.2"
    eslint: "^9.39.3"
    eslint-config-airbnb-extended: "^3.0.1"
    eslint-config-prettier: "^10.1.8"
    eslint-import-resolver-typescript: "^4.4.4"
    eslint-plugin-html: "^8.1.4"
    eslint-plugin-import-x: "^4.16.2"
    eslint-plugin-jest: "^29.15.1"
    eslint-plugin-json: "^4.0.1"
    eslint-plugin-jsx-a11y: "^6.10.2"
    eslint-plugin-no-relative-import-paths: "^1.6.1"
    eslint-plugin-prettier: "^5.5.5"
    eslint-plugin-react: "^7.37.5"
    eslint-plugin-security: "^4.0.0"
    eslint-plugin-sonarjs: "^4.0.2"
    eslint-plugin-sort-destructure-keys: "^3.0.0"
    eslint-plugin-unicorn: "^63.0.0"
    typescript-eslint: "^8.57.2"
  test:
    "@types/jest": "^29.5.14"
    jest: "^29.7.0"
    jest-environment-jsdom: "^29.7.0"
    jest-html-reporter: "^4.4.0"
    jest-mock-extended: "^4.0.0"
    lcov-result-merger: "^5.0.1"
    ts-jest: "^29.4.6"
  tools:
    "@tsconfig/node22": "^22.0.5"
    "@types/aws-lambda": "^8.10.161"
    "@types/node": "^24.12.0"
    esbuild: "^0.27.4"
    ts-node: "^10.9.2"
    tsx: "^4.21.0"
    typescript: "^5.9.3"
